### PUT 1 request with a header
PUT http://localhost:8000/api/policy/3331
Accept: application/ld+json
Content-Type: application/ld+json

{
    "odrl_policy": {
        "@context": "http://www.w3.org/ns/odrl.jsonld",
        "@type": "Offer",
        "uid": "http://example.com/policy:3331",
        "profile": "http://example.com/odrl/profile/10",
        "permission": [
            {
                "target": "https://arxiv.org/pdf/2409.17602v1",
                "assigner": "http://example.com/org/616",
                "action": "display",
                "constraint": [
                    {
                        "leftOperand": { "@value": "{{face_uuid}}", "@type": "xsd:string" },
                        "operator": "eq",
                        "rightOperand": { "@value": "a0fbc6eb-bc0d-4489-b581-f102107c86fd", "@type": "xsd:string" }
                    }
                ]
            }
        ]
    }
}



### POST 1 request with a header
POST http://localhost:8000/api/policy/
Accept: application/ld+json
Content-Type: application/ld+json
Body:

{
    "odrl_policy": {
        "@context": "http://www.w3.org/ns/odrl.jsonld",
        "@type": "Offer",
        "uid": "http://example.com/policy:3331",
        "profile": "http://example.com/odrl/profile/10",
        "permission": [
            {
                "target": "https://arxiv.org/pdf/2409.17602v1",
                "assigner": "http://example.com/org/616",
                "action": "display" ,
                "constraint": [
                    {
                        "leftOperand": { "@value": "{{face_uuid}}" , "@type": "xsd:string" },
                        "operator": "eq",
                        "rightOperand": { "@value": "03cdfe31-f81c-40b8-b30a-b273c54dd26c", "@type": "xsd:string" }
                    }
                ]
            }
        ]
    }
}


### POST 2 request with a header
POST http://localhost:8000/api/policy/
Accept: application/ld+json
Content-Type: application/ld+json
Body:

{
    "odrl_policy": {
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Offer",
    "uid": "http://example.com/policy:6165",
    "profile": "http://example.com/odrl:profile:10",
    "permission": [{
       "target": "http://example.com/document:1234",
       "assigner": "http://example.com/org:616",
       "action": "distribute",
       "constraint": [{
           "leftOperand": "dateTime",
           "operator": "lt",
           "rightOperand":  { "@value": "2025-01-01", "@type": "xsd:date" }
       },{
           "leftOperand": { "@value": "{{token}}" , "@type": "xsd:string" },
           "operator": "eq",
           "rightOperand":  { "@value": "AAA", "@type": "xsd:string" }
       }]
   }]
  }
}

### POST 3 request with a header
POST http://localhost:8000/api/policy/
Accept: application/ld+json
Content-Type: application/ld+json
Body:

{
    "odrl_policy": {
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Offer",
    "uid": "http://example.com/policy:6164",
    "profile": "http://example.com/odrl:profile:10",
    "permission": [{
       "target": "http://example.com/document:1234",
       "assigner": "http://example.com/org:616",
       "action": "distribute",
       "constraint": [{
           "leftOperand": "dateTime",
           "operator": "lt",
           "rightOperand":  { "@value": "2025-01-01", "@type": "xsd:date" }
       }]
   }]
  }
}

### POST 4 request with a header
POST http://localhost:8000/api/policy/
Accept: application/ld+json
Content-Type: application/ld+json
Body:

{
    "odrl_policy": {
    "@context": ["http://www.w3.org/ns/odrl.jsonld",{"time":"https://w3id.org/def/odre-time#"}],
    "@type": "Offer",
    "uid": "http://example.com/policy:5000",
    "profile": "https://example.com/user/12345",
    "permission": [{
       "target": "https://www.europarl.europa.eu/topics/en/article/20230601STO93804/eu-ai-act-first-regulation-on-artificial-intelligence",
       "action": "read",
       "constraint": [{
           "leftOperand": "time:time",
           "operator": "lteq",
           "rightOperand":  { "@value": "23:59:00", "@type": "xsd:time" }
       }]
   }]
}


}

### GET request with parameter
GET http://localhost:8000/api/policy/5000
Accept: application/ld+json

### GET request with a header
GET http://localhost:8000/api/policy/
Accept: application/ld+json

### DELETE request with parameter
DELETE http://localhost:8000/api/policy/3331
Accept: application/ld+json

### GET request for evaluate
GET http://localhost:8000/api/policy/evaluate/5000
Accept: application/ld+json

### GET request for evaluate
GET http://localhost:8000/api/policy/evaluate/3331?key=face_recognition&id=3331&face_uuid=cd42c43d-18c4-445f-b5a6-814bc29cb505
Accept: application/ld+json

### POST request for evaluate
POST http://localhost:8000/api/policy/evaluate?token=AAA
Accept: application/ld+json
Content-Type: application/ld+json
Body:

{
    "odrl_policy": {
    "@context": ["http://www.w3.org/ns/odrl.jsonld",{"time":"https://w3id.org/def/odre-time#"}],
    "@type": "Offer",
    "uid": "https://helio.auroral.linkeddata.es/policy/3",
    "profile": "https://example.com/user/12345",
    "permission": [{
       "target": "https://www.w3.org/TR/2018/REC-odrl-model-20180215/",
       "action": "read",
       "constraint": [{
           "leftOperand": "time:time",
           "operator": "lteq",
           "rightOperand":  { "@value": "23:59:00", "@type": "xsd:time" }
       }]
   }]
}


}





### POST 1 request for sparql
POST http://localhost:8000/api/policy/sparql
Accept: application/json
Content-Type: application/json
Body:

{
  "query": "SELECT ?policy WHERE { ?policy a <http://www.w3.org/ns/odrl/2/Offer> . } "
}

### POST 2 request for sparql
POST http://localhost:8000/api/policy/sparql
Accept: application/json
Content-Type: application/json
Body:

{
  "query": "SELECT ?policy WHERE {?policy a odrl:Offer ;odrl:permission [odrl:target <http://example.com/document:124> ] .}"
}

### POST 3 request for sparql
POST http://localhost:8000/api/policy/sparql
Accept: application/json
Content-Type: application/json
Body:

{
  "query": "SELECT ?policy ?date WHERE {?policy a odrl:Offer ;odrl:permission [odrl:constraint [odrl:leftOperand odrl:dateTime ;odrl:operator odrl:lt ;odrl:rightOperand ?date ] ] .}"
}

### POST 4 request for sparql
POST http://localhost:8000/api/policy/sparql
Accept: application/json
Content-Type: application/json
Body:

{
  "query": "SELECT ?policy ?action ?target WHERE {?policy a odrl:Set ;odrl:permission [odrl:action ?action ;odrl:target ?target ] .}"
}

