### POST 1 request with a header
POST http://localhost:8000/api/policy/
Accept: application/ld+json
Content-Type: application/ld+json
Body:

{
    "odrl_policy": {
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Set",
    "uid": "http://example.com/policy:1010",
    "permission": [{
        "target": "http://example.com/asset:9898.movie",
        "action": "use"
    }]
  }
}

### POST 2 request with a header
POST http://localhost:8000/api/policy/
Accept: application/ld+json
Content-Type: application/ld+json
Body:

{
    "odrl_policy": {
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Offer",
    "uid": "http://example.com/policy:6165",
    "profile": "http://example.com/odrl:profile:10",
    "permission": [{
       "target": "http://example.com/document:1234",
       "assigner": "http://example.com/org:616",
       "action": "distribute",
       "constraint": [{
           "leftOperand": "dateTime",
           "operator": "lt",
           "rightOperand":  { "@value": "2025-01-01", "@type": "xsd:date" }
       },{
           "leftOperand": { "@value": "{{token}}" , "@type": "xsd:string" },
           "operator": "eq",
           "rightOperand":  { "@value": "AAA", "@type": "xsd:string" }
       }]
   }]
  }
}

### POST 3 request with a header
POST http://localhost:8000/api/policy/
Accept: application/ld+json
Content-Type: application/ld+json
Body:

{
    "odrl_policy": {
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Offer",
    "uid": "http://example.com/policy:6164",
    "profile": "http://example.com/odrl:profile:10",
    "permission": [{
       "target": "http://example.com/document:1234",
       "assigner": "http://example.com/org:616",
       "action": "distribute",
       "constraint": [{
           "leftOperand": "dateTime",
           "operator": "lt",
           "rightOperand":  { "@value": "2025-01-01", "@type": "xsd:date" }
       }]
   }]
  }
}

### POST 4 request with a header
POST http://localhost:8000/api/policy/
Accept: application/ld+json
Content-Type: application/ld+json
Body:

{
    "odrl_policy": {
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Offer",
    "uid": "http://example.com/policy:5",
    "profile": "https://helio.auroral.linkeddata.es/jcano",
    "permission": [{
       "target": "https://helio.auroral.linkeddata.es/api/luminosity/data",
       "action": "read",
       "constraint": [{
           "leftOperand": { "@value": "{{status('switch', 'https://helio.auroral.linkeddata.es/policy/5')}}" , "@type": "xsd:string" },
           "operator": "eq",
           "rightOperand":  { "@value": "On", "@type": "xsd:string" }
       }]
   }]
  }
}


### GET request with parameter
GET http://localhost:8000/api/policy/5
Accept: application/ld+json

### GET request with a header
GET http://localhost:8000/api/policy/
Accept: application/ld+json

### DELETE request with parameter
DELETE http://localhost:8000/api/policy/1010
Accept: application/ld+json

### GET request for evaluate
GET http://localhost:8000/api/policy/evaluate/5?key=status_var&id=5
Accept: application/ld+json

### POST request for evaluate
POST http://localhost:8000/api/policy/evaluate?token=AAA
Accept: application/ld+json
Content-Type: application/ld+json
Body:

{
    "odrl_policy": {
        "@context": "http://www.w3.org/ns/odrl.jsonld",
        "@type": "Offer",
        "uid": "http://example.com/policy:6165",
        "profile": "http://example.com/odrl:profile:10",
        "permission": [{
            "target": "http://example.com/document:1234",
            "assigner": "http://example.com/org:616",
            "action": "distribute",
            "constraint": [{
                "leftOperand": "dateTime",
                "operator": "lt",
                "rightOperand": { "@value": "2025-01-01", "@type": "xsd:date" }
            }, {
                "leftOperand": { "@value": "{{token}}", "@type": "xsd:string" },
                "operator": "eq",
                "rightOperand": { "@value": "AAA", "@type": "xsd:string" }
            }]
        }]
    }
}




### POST 1 request for sparql
POST http://localhost:8000/api/policy/sparql
Accept: application/json
Content-Type: application/json
Body:

{
  "query": "SELECT ?policy WHERE { ?policy a <http://www.w3.org/ns/odrl/2/Offer> . } "
}

### POST 2 request for sparql
POST http://localhost:8000/api/policy/sparql
Accept: application/json
Content-Type: application/json
Body:

{
  "query": "SELECT ?policy WHERE {?policy a odrl:Offer ;odrl:permission [odrl:target <http://example.com/document:124> ] .}"
}

### POST 3 request for sparql
POST http://localhost:8000/api/policy/sparql
Accept: application/json
Content-Type: application/json
Body:

{
  "query": "SELECT ?policy ?date WHERE {?policy a odrl:Offer ;odrl:permission [odrl:constraint [odrl:leftOperand odrl:dateTime ;odrl:operator odrl:lt ;odrl:rightOperand ?date ] ] .}"
}

### POST 4 request for sparql
POST http://localhost:8000/api/policy/sparql
Accept: application/json
Content-Type: application/json
Body:

{
  "query": "SELECT ?policy ?action ?target WHERE {?policy a odrl:Set ;odrl:permission [odrl:action ?action ;odrl:target ?target ] .}"
}

